### PR TITLE
improve pid related

### PR DESCRIPTION
**Pull request by wwwjfy**
- is_running: use os.kill to check if it's still running
- delpid: remove pidfile only if it matches self pid

### CODE REVIEW

**Comment by carlosperello** [comment]
Hi, the problem with this branch is that we require this code to be compatible with python 2.4 so your exception code change breaks such compatibility.

I don't think this code is complex enough to justify two different files to support 2.4 and 3.x so... what about using this other approach?

http://stackoverflow.com/questions/12682558/how-to-write-an-exception-catching-code-works-in-python2-4-to-python3

**Comment by wwwjfy** [comment]
I last used Python 2.4 very long ago, and I think we should do best to catch up, so I'm sorry I don't want to introduce the hack for that.

This branch is mostly code style fix, so if Python 2.4 is a must, I think it can be ignored.

**Comment by carlosperello** [comment]
I agree that we should leave 2.4 rest as soon as possible, however we use this code as part of our monitor client and we support old RedHat and CentOS releases that still get security updates and that include python 2.4 so we need to support it until they reach EOL.

**Comment by carlosperello** [comment]
The Python 2.4 requirement is not valid anymore so I just merged this. Thanks

**Pull request merged**
